# Generated by Django 2.2 on 2022-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
