# Generated by Django 2.2 on 2022-02-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_drink_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drinks',
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drink', to='app_1.Drink'),
        ),
    ]
